name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install -r requirements.txt

    - name: Run Tests
      run: |
        export PYTHONPATH=src
        pytest --cov=api tests/unit --cov-report=xml:coverageResultPath --junitxml=unitTestResultPath